source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
export PATH="/usr/local/bin:$PATH"
#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

# Prezto Settings
setopt no_share_history
unsetopt share_history

source "$HOME/Github/dotfiles/zsh/spaceship.zsh"

source "$HOME/.zprofile"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# If fortune is installed, run a fortune
if [ -e /usr/local/bin/fortune ]; then
    fortune -s
    echo " "
fi

# Ignore certain paths in CD
export FIGNORE="Application Scripts:ScriptingAdditions"

# Single-brace syntax because this is required in bash and sh alike
if [ -e "$HOME/env/etc/indeedrc" ]; then
    . "$HOME/env/etc/indeedrc"
fi

# Remove hyphen as part of words
# https://gist.github.com/anchor/4076792
autoload -U select-word-style
select-word-style bash

### Functions ###

# cd to the path of the front Finder window
cdf() {
  target=`osascript -e 'tell application "Finder" to if (count of Finder windows) > 0 then get POSIX path of (target of front Finder window as text)'`
  if [ "$target" != "" ]; then
    cd "$target"; pwd
  else
    echo 'No Finder window found' >&2
  fi
}

# open a specified man page in Preview
man-preview() {
  man -t "$@" | open -f -a Preview
}

# move a specified file to the OSX Trash
trash() {
  local trash_dir="${HOME}/.Trash"
  local temp_ifs=$IFS
  IFS=$'\n'
  for item in "$@"; do
    if [[ -e "$item" ]]; then
      item_name="$(basename $item)"
      if [[ -e "${trash_dir}/${item_name}" ]]; then
        mv -f "$item" "${trash_dir}/${item_name} $(date "+%H-%M-%S")"
      else
        mv -f "$item" "${trash_dir}/"
      fi
    fi
  done
  IFS=$temp_ifs
}

# # notify on completion, from http://frantic.im/notify-on-completion
# function f_notifyme {
#   LAST_EXIT_CODE=$?
#   CMD=$(fc -ln -1)
#   # No point in waiting for the command to complete
#   notifyme "$CMD" "$LAST_EXIT_CODE" &
# }
# # inject this function in front of every command
# export PS1='$(f_notifyme)'$PS1

# git clone and cd into the new directory
# combo of these two solutions:
# https://unix.stackexchange.com/a/276483
# https://stackoverflow.com/a/12059200
git(){
  case "$1" in
    (clone) git-clone "${@:2}";;
    (*) command git "$@";;
  esac
}
git-clone(){
    url=$1;
    reponame=$(echo $url | awk -F/ '{print $NF}' | sed -e 's/.git$//');
    command git clone $url $reponame;
    cd $reponame;
}
# Hot gif action
# From https://gist.github.com/brianloveswords/7534169715b5750a892cddcf54c2aa0e
video-url-from-tweet() {
    if [ "$1" ]; then
        url=$1
    else
        echo "Must provide a url"
        return 1
    fi

    curl --silent $url |\
        # should find the <meta> tag with content="<thumbnail url>"
        (grep -m1 "tweet_video_thumb" ||\
          echo "Could not find video" && return 1) |\

        ## It looks like Twitter changed some page format things, this is now the old and busted  
        ## from: <meta property="og:image" content="https://pbs.twimg.com/tweet_video_thumb/xxxxxxxxxx.jpg">
        ## to: https://pbs.twimg.com/tweet_video_thumb/xxxxxxxxxx.jpg
        #cut -d '"' -f 4 |\

        ## This is now the new hotness
        # from: <img src="https://pbs.twimg.com/tweet_video_thumb/D7z5JahXsAEkH_z.jpg:small"/>
        # to: https://pbs.twimg.com/tweet_video_thumb/D7z5JahXsAEkH_z.jpg:small
        cut -d '"' -f 2 |\

        # from: https://pbs.twimg.com/tweet_video_thumb/xxxxxxxxxx.jpg
        # to: https://video.twimg.com/tweet_video/xxxxxxxxxx.mp4
        sed 's/.jpg:small/.mp4/g' |\
        sed 's/pbs.twimg.com\/tweet_video_thumb/video.twimg.com\/tweet_video/g'
}
video-from-tweet() {
    if [ "$1" ]; then
        url=$1
    else
        echo "Must provide a url"
        return 1
    fi
    curl $(video-url-from-tweet $url)
}
video-to-gif() {
    # derived from https://engineering.giphy.com/how-to-make-gifs-with-ffmpeg/
    if [ "$2" ]; then
        input=$1
        output=$2
    else
        echo "Must provide an input file and output file"
        return 1
    fi

    ffmpeg -i $input \
           -filter_complex "[0:v] split [a][b];[a] palettegen [p];[b][p] paletteuse" \
           -f gif \
           $output
}
gif-from-tweet() {
    if [ "$2" ]; then
        url=$1
        output=$2
    else
        echo "Must provide a url and an output filename"
        return 1
    fi
    video-from-tweet $url | video-to-gif - $output
}

### Aliases ###
# list out apps installed by homebrew
alias brews='echo -- "brews --------------------" && brew list && echo "-- casks -----------------" && brew cask list'

# list of all out of date homebrew apps
alias brewu='brew outdated'

# list of all globally installed npm apps
alias npms='npm list -g --depth 0'

# open Finder window to current path
alias finder='open -a Finder ./'

# alias ls -la to ll
alias ll='ls -la --color=auto'

# alias git status -sb to st
alias st='git st'

# always highlight grep search term
alias grep='grep --color=auto'

# Dock Spacer on the application side
# Pre-Sierra
# alias dockspacer="defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type=\"spacer-tile\";}'"
# Sierra
alias dockspacer="defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="spacer-tile";}'; killall Dock"
# Dock Spacer on the other side
# Pre-Sierra
# alias dockspacer-other="defaults write com.apple.dock persistent-others -array-add '{tile-data={}; tile-type=\"spacer-tile\";}'"
# Sierra
alias dockspacer-other="defaults write com.apple.dock persistent-others -array-add '{"tile-type"="spacer-tile";}'; killall Dock"

# DNS flushing for dnsmasq purposes
alias flushdns='dscacheutil -flushcache'

# reload zsh config
# alias reload='source ~/.zshrc'
alias reload='exec zsh'

# run multitail -c
alias tailc='multitail -c'
alias mtail='multitail -c'

# force mtr to be sudo-run
alias mtr='sudo mtr'

# shortcut to display file sizes in terminal
#alias sizes="du -sh * | sort -n"

# sublime text shortcut
alias subl="sublime"

# better name for https://gist.github.com/brianloveswords/7534169715b5750a892cddcf54c2aa0e
alias tweetgif="gif-from-tweet"

# the following three are from https://remysharp.com/2018/08/23/cli-improved
# ncdu with some prettification
alias du="ncdu --color dark -rr -x --exclude .git --exclude node_modules"

# prettyping with ping limits
alias ping='prettyping -c 5 --nolegend'

# bat for cat purposes
alias cat='bat'

# Quick Look a file from Terminal
alias ql="qlmanage -px &>/dev/null"

# copy the working directory path
alias cpwd='pwd|tr -d "\n"|pbcopy'

# retrieve current external ip
alias myip='curl -4 https://icanhazip.com'

# weather and the moon from @noopkat
alias weather='curl -4 https://wttr.in/Austin'
alias moon='curl -4 https://wttr.in/Moon'
