// purple-readable.glsl — generated by lib/generate.sh
// Edit lib/template.glsl or lib/presets.json and re-run, do not edit this file.
// preset: purple   tier: readable   tint: vec3(0.85, 0.4, 1.2)
// knobs: MIX_ORIG=0.30  TONEMAP_K=0.50  BRIGHT_THRESH=0.35

// Shared template for ghostty-crt-shaders.
// Generated files in shaders/ are produced from this template +
// lib/presets.json by lib/generate.sh.
//
// Per-fragment cost (identical across every generated variant):
//   - 5 texture(iChannel0, ...) samples (1 center + 4 cardinal cross).
//   - 5x dot(rgb, LUMA) luminance conversions.
//   - 5x smoothstep() bright-pass gates (dark cells don't glow).
//   - 1x mix() with original RGB (preserves colored-UI legibility).
//   - 1x vec3 / (1 + vec3 * k) Reinhard tonemap (rolls off blowouts).
//   - polynomial vignette + 2 sin() for scanline + flicker.
//
// Per WWDC20 "Optimize Metal apps and games", post-processing on
// Apple Silicon is texture-sampler-limited; ALU is plentiful. Holding
// texture samples constant at 5 means every variant has identical GPU
// cost regardless of color or tier.

const vec3  LUMA          = vec3(0.299, 0.587, 0.114);
const vec3  PHOSPHOR      = vec3(0.85, 0.4, 1.2);
const float GLOW_OFFSET   = 0.0015;
const float GLOW_CENTER_W = 1.6;
const float GLOW_CROSS_W  = 0.45;
const float BRIGHT_SOFT   = 0.20;

const float MIX_ORIG      = 0.30;
const float TONEMAP_K     = 0.50;
const float BRIGHT_THRESH = 0.35;
const float SCANLINE_AMP  = 0.02;
const float FLICKER_AMP   = 0.01;

vec3 sampleRgb(vec2 uv) { return texture(iChannel0, uv).rgb; }
float lumOf(vec3 c) { return dot(c, LUMA); }
float gatedLum(vec2 uv) {
    float l = lumOf(sampleRgb(uv));
    return l * smoothstep(BRIGHT_THRESH, BRIGHT_THRESH + BRIGHT_SOFT, l);
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;
    vec3 centerRgb = sampleRgb(uv);
    float cLum = lumOf(centerRgb);
    float cGate = cLum * smoothstep(BRIGHT_THRESH, BRIGHT_THRESH + BRIGHT_SOFT, cLum);

    float g = cGate * GLOW_CENTER_W
            + (gatedLum(uv + vec2(GLOW_OFFSET, 0.0))
             + gatedLum(uv - vec2(GLOW_OFFSET, 0.0))
             + gatedLum(uv + vec2(0.0, GLOW_OFFSET))
             + gatedLum(uv - vec2(0.0, GLOW_OFFSET))) * GLOW_CROSS_W;

    vec2 vig = uv * (1.0 - uv.yx);
    float bgGlow = 0.2 * pow(clamp(vig.x * vig.y * 15.0, 0.0, 1.0), 0.5);
    vec3 bgColor = PHOSPHOR * bgGlow * 0.4;

    float scanline = (1.0 - SCANLINE_AMP) + SCANLINE_AMP * sin(uv.y * iResolution.y * 3.1415 * 1.5);
    float flicker  = (1.0 - FLICKER_AMP)  + FLICKER_AMP  * sin(iTime * 100.0);

    vec3 color = bgColor + PHOSPHOR * g * scanline * flicker;
    color = mix(color, centerRgb, MIX_ORIG);
    color = color / (1.0 + color * TONEMAP_K);

    fragColor = vec4(color, 1.0);
}
